all: problem_a.c problem_b.c problem_c.c problem_d.c
	gcc problem_a.c -o problem_a -Wall -g
	gcc problem_b.c -o problem_b -Wall -g
	gcc problem_c.c -o problem_c -Wall -g
	gcc problem_d.c -o problem_d -Wall -g

clean:
	rm problem_a problem_b problem_c problem_d